# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login_location', jsonfield.fields.JSONField(null=True)),
                ('logo', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2017, 4, 21, 13, 50, 13, 149808))),
                ('updated_at', models.DateTimeField(verbose_name=datetime.datetime(2017, 4, 21, 13, 50, 13, 149852))),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
